### ISSUE TITLE
New install errors on npm run build

### ISSUE THREAD

**Issue by eric7186** [bacoords/block-theme#261]
I just installed this theme and activated it on  a new dev site (nginx, PHP 8.1.23, MySQL 8.0.16, WP 6.5.3) running under Local by Flywheel 9.0.3. When I open a terminal (in VS Code 1.89.1) to the theme directory and run the command: npm run build, I get this error:
themes\block-theme> npm run build

> block-theme@0.0.2 build
> wp-scripts build --config ./bin/webpack.config.js --webpack-src-dir=src/blocks

[webpack-cli] Error: Unknown option '--webpack-src-dir=src/blocks'
[webpack-cli] Run 'webpack --help' to see available commands and options

WordPress 6.5.3
npm 10.2.4
node v21.6.1

**Comment by bacoords** [comment]
Can you share the output from running `npm install` to see if there were any issues installing any of the packages?

**Comment by eric7186** [comment]
Ah, I just needed to execute npm install first. Then npm run build completed successfully.

**Comment by bacoords** [comment]
Great! I've added this command to the `readme` file as well just to be sure.
