### ISSUE TITLE
Reference SCSS variables from blocks

### ISSUE THREAD

**Issue by YarGnawh** [bacoords/block-theme#269]
Is the following possible?

```
src
  / blocks
    / hello-world
      / styles.scss       << reference SCSS variable

  / scss
    / base
      / variables.scss    << defined here
```

**Comment by bacoords** [comment]
Yes definitely. It depends on the folders so this might not be perfect but something along the lines of `@use '../../scss/base/variables'` at the top of the `styles.scss` file should work.

**Comment by YarGnawh** [comment]
@bacoords that works! i tried messing with the SASS load path in the webpack config but couldn't get it to work. hopefully someone with more experience can figure it out.
